/* Ajustar columnas según la estructura exacta restaurada del .bak */
CREATE OR ALTER FUNCTION dbo.fn_ListarClientes()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.CLIENTE WHERE ISNULL(Activo, 1) = 1;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerClientePorId(@ClienteID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.CLIENTE WHERE ClienteID = @ClienteID;
GO

CREATE OR ALTER FUNCTION dbo.fn_ListarProductos()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.PRODUCTO;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerProductoPorId(@ProductoID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.PRODUCTO WHERE ProductoID = @ProductoID;
GO

CREATE OR ALTER FUNCTION dbo.fn_ListarCuentas()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.CUENTA;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerCuentaPorId(@CuentaID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.CUENTA WHERE CuentaID = @CuentaID;
GO

CREATE OR ALTER FUNCTION dbo.fn_ListarPrestamos()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.PRESTAMO;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerPrestamoPorId(@PrestamoID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.PRESTAMO WHERE PrestamoID = @PrestamoID;
GO

CREATE OR ALTER FUNCTION dbo.fn_ListarTarjetas()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.TARJETA;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerTarjetaPorId(@TarjetaID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.TARJETA WHERE TarjetaID = @TarjetaID;
GO

CREATE OR ALTER FUNCTION dbo.fn_ListarTransacciones()
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.TRANSACCION;
GO

CREATE OR ALTER FUNCTION dbo.fn_ObtenerTransaccionPorId(@TransaccionID INT)
RETURNS TABLE
AS
RETURN SELECT * FROM dbo.TRANSACCION WHERE TransaccionID = @TransaccionID;
GO
